SELECT HISTORY_ID,
       ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE,H.START_DATE) + 1) * (1- CASE WHEN P.DISCOUNT_RATE IS NULL THEN 0 ELSE P.DISCOUNT_RATE END/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON P.CAR_TYPE = C.CAR_TYPE
AND CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
         WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
         WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
         END = P.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC



# SELECT  B.HISTORY_ID
#         ,ROUND(A.DAILY_FEE * (DATEDIFF(B.END_DATE,B.START_DATE) + 1) * (1- CASE WHEN DISCOUNT_RATE IS NULL THEN 0 ELSE DISCOUNT_RATE END/100)) AS FEE
#   FROM  CAR_RENTAL_COMPANY_CAR A
#   JOIN  CAR_RENTAL_COMPANY_RENTAL_HISTORY B
#     ON  A.CAR_ID = B.CAR_ID
#   LEFT
#   JOIN  CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
#     ON  A.CAR_TYPE = C.CAR_TYPE
#         AND CASE WHEN DATEDIFF(B.END_DATE,B.START_DATE) + 1 >= 90 THEN '90일 이상'
#                  WHEN DATEDIFF(B.END_DATE,B.START_DATE) + 1 >= 30 THEN '30일 이상'
#                  WHEN DATEDIFF(B.END_DATE,B.START_DATE) + 1 >= 7 THEN '7일 이상' END = C.DURATION_TYPE
#  WHERE  A.CAR_TYPE = '트럭'
#  ORDER
#     BY  2 DESC, 1 DESC
